var dataTabella1 = {
  "1": [
    {
      "Identificazione Strada": "Lungotevere Vaticano (sottopasso)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1292.8,
      "Flusso Min": 1290.97,
      "Flusso Max": 1296.92,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Piazza di Santa Maria Liberatrice",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4032.43,
      "Flusso Min": 1614.12,
      "Flusso Max": 5952.69,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Piazza Pia",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 1292.33,
      "Flusso Min": 1291.41,
      "Flusso Max": 1293.08,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Beniamino Franklin",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.37,
      "Flusso medio": 4169.91,
      "Flusso Min": 789.46,
      "Flusso Max": 9543.46,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Cairoli",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.16,
      "Flusso medio": 4750.2,
      "Flusso Min": 321.81,
      "Flusso Max": 20692.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Damiata",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4929.82,
      "Flusso Min": 933.46,
      "Flusso Max": 8882.42,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via del Mascherino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2852.8,
      "Flusso Min": 2416.96,
      "Flusso Max": 3890.65,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via delle Terme di Tito",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2850.46,
      "Flusso Min": 2287.27,
      "Flusso Max": 3328.04,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Edmondo De Amicis",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1.0,
      "Flusso medio": 2265.83,
      "Flusso Min": 1880.08,
      "Flusso Max": 2928.35,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1, 15"
    },
    {
      "Identificazione Strada": "Via Farini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4611.04,
      "Flusso Min": 3748.96,
      "Flusso Max": 5523,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Filippo Corridoni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.98,
      "Flusso medio": 3744.95,
      "Flusso Min": 372.35,
      "Flusso Max": 5302.62,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Giovanni Branca",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2768.63,
      "Flusso Min": 1294.5,
      "Flusso Max": 5391.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Gomenizza",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3460.86,
      "Flusso Min": 788.54,
      "Flusso Max": 6636.23,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Muggia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1980.2,
      "Flusso Min": 592.04,
      "Flusso Max": 3186.46,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Nicola Fabrizi",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.61,
      "Flusso medio": 3613.54,
      "Flusso Min": 2282.65,
      "Flusso Max": 5048.19,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Ottaviano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 349.73,
      "Flusso Min": 321.92,
      "Flusso Max": 377.54,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Palestro (Cernaia-S.M. Della Battaglia)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3403.19,
      "Flusso Min": 2510.31,
      "Flusso Max": 5065.27,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Teulada",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.98,
      "Flusso medio": 3023.92,
      "Flusso Min": 80.08,
      "Flusso Max": 4200.35,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Timavo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.92,
      "Flusso medio": 3910.47,
      "Flusso Min": 141.69,
      "Flusso Max": 11638.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Tomacelli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.53,
      "Flusso medio": 3156.45,
      "Flusso Min": 470.77,
      "Flusso Max": 6001.15,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Via Trionfale (C.ne Clodia-Evangelisti)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4134.26,
      "Flusso Min": 2584.27,
      "Flusso Max": 10907.88,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1, 14"
    },
    {
      "Identificazione Strada": "Viale Angelico",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.94,
      "Flusso medio": 4570.38,
      "Flusso Min": 6.23,
      "Flusso Max": 13780.96,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Viale Carso",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2292.19,
      "Flusso Min": 658.15,
      "Flusso Max": 4209.69,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Viale del Monte Oppio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.81,
      "Flusso medio": 4166.58,
      "Flusso Min": 1389.46,
      "Flusso Max": 16924.85,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Viale Manlio Gelsomini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.77,
      "Flusso medio": 3632.27,
      "Flusso Min": 147.35,
      "Flusso Max": 8577.46,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "1"
    },
    {
      "Identificazione Strada": "Piazza Pio XII",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": 1
    },
    {
      "Identificazione Strada": "Ponte Giuseppe Mazzini",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": 1
    },
    {
      "Identificazione Strada": "Via Rubattino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 1
    },
    {
      "Identificazione Strada": "Via Urbano VIII",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 1
    },
    {
      "Identificazione Strada": "Viale della Trinità dei Monti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 1
    }
  ],
  "2": [
    {
      "Identificazione Strada": "Via Alessandro Torlonia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4804.09,
      "Flusso Min": 2115.46,
      "Flusso Max": 8432.19,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Anapo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3653.72,
      "Flusso Min": 2180.31,
      "Flusso Max": 5564.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Asmara",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4625.28,
      "Flusso Min": 1318.15,
      "Flusso Max": 9466.62,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Dalmazia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3137.45,
      "Flusso Min": 597.23,
      "Flusso Max": 9565.96,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via dei Liburni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3102.46,
      "Flusso Min": 2212.27,
      "Flusso Max": 3992.65,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Flaminia (Fracassini-Ponte Milvio)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.79,
      "Flusso medio": 3033.28,
      "Flusso Min": 269.54,
      "Flusso Max": 7439.08,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Guido Reni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 2295.01,
      "Flusso Min": 47.88,
      "Flusso Max": 4161.23,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Lorenzo il Magnifico",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.89,
      "Flusso medio": 3393.66,
      "Flusso Min": 376.96,
      "Flusso Max": 10326.92,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2, 4"
    },
    {
      "Identificazione Strada": "Via Magliano Sabina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4944.83,
      "Flusso Min": 2268.58,
      "Flusso Max": 10879.27,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Nizza",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3744.81,
      "Flusso Min": 3744.81,
      "Flusso Max": 3744.81,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Postumia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.64,
      "Flusso medio": 4322.97,
      "Flusso Min": 1950.69,
      "Flusso Max": 8120.65,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Ridolfino Venuti",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.36,
      "Flusso medio": 3131.09,
      "Flusso Min": 265.15,
      "Flusso Max": 12398.77,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Via Rovigo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.82,
      "Flusso medio": 1946.7,
      "Flusso Min": 1211.54,
      "Flusso Max": 4741.04,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Viale Tiziano (Via C.Fracassini-Ponte Milvio)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ; Q",
      "% PGTU": 0.8,
      "Flusso medio": 3947.63,
      "Flusso Min": 254.77,
      "Flusso Max": 10060.73,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2"
    },
    {
      "Identificazione Strada": "Viale Giorgio Washington",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "Si",
      "Municipio": 2
    }
  ],
  "3": [
    {
      "Identificazione Strada": "Piazza Filattiera",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4321.6,
      "Flusso Min": 3182.54,
      "Flusso Max": 6197.42,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Piazza Minucciano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4036.76,
      "Flusso Min": 160.62,
      "Flusso Max": 5786.31,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Comano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4007.76,
      "Flusso Min": 2996.42,
      "Flusso Max": 5031.58,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Cortona (Svincolo Salaria-Radicofani)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.91,
      "Flusso medio": 4361.91,
      "Flusso Min": 341.54,
      "Flusso Max": 5387.42,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via della Marcigliana",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.21,
      "Flusso medio": 206.42,
      "Flusso Min": 49.27,
      "Flusso Max": 555.23,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via delle Isole Curzolane",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 4299.09,
      "Flusso Min": 18.81,
      "Flusso Max": 5673,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via di Tor San Giovanni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 2279.42,
      "Flusso Min": 318.69,
      "Flusso Max": 4919.08,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Don Giustino Maria Russolillo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2711.02,
      "Flusso Min": 2285.54,
      "Flusso Max": 3151.27,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Filippo Antonio Gualterio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 2979.7,
      "Flusso Min": 1188.58,
      "Flusso Max": 3920.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Incisa in Val d'Arno",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 920.49,
      "Flusso Min": 52.62,
      "Flusso Max": 3271.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Molazzana",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4073.99,
      "Flusso Min": 3092.54,
      "Flusso Max": 5149.85,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Monte Cervialto",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.8,
      "Flusso medio": 4813.1,
      "Flusso Min": 8.65,
      "Flusso Max": 9551.42,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Monte Grimano",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3247.88,
      "Flusso Min": 366.92,
      "Flusso Max": 4281,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Radicofani",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 3078.04,
      "Flusso Min": 153.81,
      "Flusso Max": 5092.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Salaria (tratto abitato Settebagni)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.82,
      "Flusso medio": 4460.33,
      "Flusso Min": 313.62,
      "Flusso Max": 16661.49,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via San Leo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2996.22,
      "Flusso Min": 2704.38,
      "Flusso Max": 3376.27,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Seggiano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.74,
      "Flusso medio": 3873.83,
      "Flusso Min": 591.81,
      "Flusso Max": 6127.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Val Brembana",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.69,
      "Flusso medio": 4814.49,
      "Flusso Min": 1219.38,
      "Flusso Max": 7157.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Val di Lanzo",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3932.32,
      "Flusso Min": 412.38,
      "Flusso Max": 11475.81,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Valsesia",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4433.39,
      "Flusso Min": 4338.58,
      "Flusso Max": 4511.31,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Viale Carmelo Bene",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.98,
      "Flusso medio": 2765.59,
      "Flusso Min": 1.15,
      "Flusso Max": 10236.69,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Viale Gino Cervi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2853.37,
      "Flusso Min": 2253.12,
      "Flusso Max": 3635.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Viale Titina De Filippo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.95,
      "Flusso medio": 4840.8,
      "Flusso Min": 222.12,
      "Flusso Max": 7883.88,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "3"
    },
    {
      "Identificazione Strada": "Via Val Maira",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 3
    }
  ],
  "4": [
    {
      "Identificazione Strada": "Via Ciciliano",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 1379.81,
      "Flusso Min": 241.1,
      "Flusso Max": 1707.66,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Via dei Durantini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4238.38,
      "Flusso Min": 1318.15,
      "Flusso Max": 7115.42,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Via di Casal de' Pazzi",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.86,
      "Flusso medio": 3288.97,
      "Flusso Min": 174.92,
      "Flusso Max": 5135.81,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Via di Sant'Alessandro",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.54,
      "Flusso medio": 4530.9,
      "Flusso Min": 40.04,
      "Flusso Max": 15843.46,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Via di Tor Cervara",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4691.45,
      "Flusso Min": 2624.88,
      "Flusso Max": 8152.85,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4, 5"
    },
    {
      "Identificazione Strada": "Via Giovanni Palombini",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 3557.36,
      "Flusso Min": 146.88,
      "Flusso Max": 3938.91,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Via Lorenzo il Magnifico",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.89,
      "Flusso medio": 3393.66,
      "Flusso Min": 376.96,
      "Flusso Max": 10326.92,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "2, 4"
    },
    {
      "Identificazione Strada": "Viale Battista Bardanzellu",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3342.25,
      "Flusso Min": 305.54,
      "Flusso Max": 5806.62,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Viale Ettore Franceschini",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4158.97,
      "Flusso Min": 33,
      "Flusso Max": 10015.85,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "4"
    },
    {
      "Identificazione Strada": "Viale Fernando Santi",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3528.81,
      "Flusso Min": 349.04,
      "Flusso Max": 4993.04,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4"
    }
  ],
  "5": [
    {
      "Identificazione Strada": "Via Angelo Viscogliosi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.89,
      "Flusso medio": 3932.93,
      "Flusso Min": 1081.27,
      "Flusso Max": 5772.23,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Aristide Staderini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4626.87,
      "Flusso Min": 1476.58,
      "Flusso Max": 6736.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Davide Campari",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 3576.63,
      "Flusso Min": 876.46,
      "Flusso Max": 6141.92,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via dei Castani",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3078.65,
      "Flusso Min": 327.35,
      "Flusso Max": 4820.77,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via dei Meli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3009.93,
      "Flusso Min": 2181.81,
      "Flusso Max": 3894.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via dei Platani",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.81,
      "Flusso medio": 2553.91,
      "Flusso Min": 639,
      "Flusso Max": 5350.38,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via delle Camelie",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.43,
      "Flusso medio": 3583.24,
      "Flusso Min": 2092.5,
      "Flusso Max": 6231.58,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via di Tor Cervara",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4691.45,
      "Flusso Min": 2624.88,
      "Flusso Max": 8152.85,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "4, 5"
    },
    {
      "Identificazione Strada": "Via di Tor Sapienza",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3909.95,
      "Flusso Min": 1459.5,
      "Flusso Max": 5028.46,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Filippo Parlatore",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.69,
      "Flusso medio": 3721.93,
      "Flusso Min": 2990.19,
      "Flusso Max": 5274.58,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Giovanni Gussone",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3774.99,
      "Flusso Min": 3264.46,
      "Flusso Max": 4212.35,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Girolamo Cocconi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.97,
      "Flusso medio": 3301.82,
      "Flusso Min": 1389.46,
      "Flusso Max": 6128.77,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Michele Tenore",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2127.06,
      "Flusso Min": 2002.73,
      "Flusso Max": 2277.58,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Molfetta",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4410.93,
      "Flusso Min": 3154.5,
      "Flusso Max": 5550.81,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Roberto Malatesta",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.97,
      "Flusso medio": 2929.82,
      "Flusso Min": 94.04,
      "Flusso Max": 4232.88,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Teano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4817.59,
      "Flusso Min": 27,
      "Flusso Max": 8109.81,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Via Tor de' Schiavi (Gelsi-Casilina)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.69,
      "Flusso medio": 2820.9,
      "Flusso Min": 503.42,
      "Flusso Max": 14878.73,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale Alessandrino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 4079.0,
      "Flusso Min": 2231.42,
      "Flusso Max": 6599.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale Antonio Averulino Filarete",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.94,
      "Flusso medio": 4387.73,
      "Flusso Min": 203.54,
      "Flusso Max": 9866.42,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale della Bella Villa",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 2607.45,
      "Flusso Min": 206.77,
      "Flusso Max": 5301.46,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale della Stazione Prenestina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.48,
      "Flusso medio": 1762.41,
      "Flusso Min": 30.69,
      "Flusso Max": 4052.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale della Venezia Giulia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 3634.84,
      "Flusso Min": 1354.62,
      "Flusso Max": 8703.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "5"
    },
    {
      "Identificazione Strada": "Viale Giovanni Battista Valente",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3056.44,
      "Flusso Min": 851.42,
      "Flusso Max": 3679.04,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "5"
    }
  ],
  "6": [
    {
      "Identificazione Strada": "Via Acquaroni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.43,
      "Flusso medio": 2087.38,
      "Flusso Min": 115.27,
      "Flusso Max": 4445.77,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Amico Aspertini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.97,
      "Flusso medio": 2445.32,
      "Flusso Min": 195.12,
      "Flusso Max": 5546.08,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Avola",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1548.17,
      "Flusso Min": 1084.27,
      "Flusso Max": 1892.08,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Castelvetrano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2823.8,
      "Flusso Min": 2192.19,
      "Flusso Max": 3763.38,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Corot",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2416.89,
      "Flusso Min": 592.15,
      "Flusso Max": 2979,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Degas",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2307.14,
      "Flusso Min": 77.42,
      "Flusso Max": 4826.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via dei Coribanti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 322.54,
      "Flusso Min": 244.27,
      "Flusso Max": 443.88,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via del Casale di Santa Maria",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.73,
      "Flusso medio": 772.21,
      "Flusso Min": 31.62,
      "Flusso Max": 1190.08,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via del Fosso dell'Osa",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.96,
      "Flusso medio": 4416.94,
      "Flusso Min": 1399.73,
      "Flusso Max": 31462.15,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via del Fosso di Santa Maura (Torre Maura-T.Spaccata)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4968.85,
      "Flusso Min": 4486.85,
      "Flusso Max": 5587.04,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via del Fuoco Sacro",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.93,
      "Flusso medio": 3869.84,
      "Flusso Min": 1056.46,
      "Flusso Max": 5374.62,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via del Torraccio di Torrenova",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2212.69,
      "Flusso Min": 1475.19,
      "Flusso Max": 4966.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via della Lite",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 660.4,
      "Flusso Min": 470.65,
      "Flusso Max": 941.31,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via dell'Acqua Vergine",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3509.56,
      "Flusso Min": 531.92,
      "Flusso Max": 4498.04,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via dell'Archeologia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2788.33,
      "Flusso Min": 2033.88,
      "Flusso Max": 7405.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via dell'Osteria del Finocchio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4376.78,
      "Flusso Min": 3592.04,
      "Flusso Max": 5498.54,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via di Carcaricola",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.84,
      "Flusso medio": 1257.43,
      "Flusso Min": 115.85,
      "Flusso Max": 2381.77,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via di Fontana Candida",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.97,
      "Flusso medio": 4089.84,
      "Flusso Min": 429.81,
      "Flusso Max": 5574.35,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via di Lunghezza (Via del Casalone-Fuori città)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 3529.23,
      "Flusso Min": 2935.96,
      "Flusso Max": 4015.73,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via di Prataporci",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 3630.09,
      "Flusso Min": 127.5,
      "Flusso Max": 6035.65,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via di Vermicino (Via Casilina-Via Bronte)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.98,
      "Flusso medio": 4971.03,
      "Flusso Min": 1384.73,
      "Flusso Max": 12708.74,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Laerte",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 549.12,
      "Flusso Min": 3,
      "Flusso Max": 932.88,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Lentini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.83,
      "Flusso medio": 1384.32,
      "Flusso Min": 159.92,
      "Flusso Max": 2360.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Luciano Conti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1409.57,
      "Flusso Min": 836.77,
      "Flusso Max": 2072.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Luigi Gastinelli",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 4455.95,
      "Flusso Min": 277.85,
      "Flusso Max": 4922.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Massa di San Giuliano",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4592.78,
      "Flusso Min": 3405.46,
      "Flusso Max": 6157.15,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Matté Trucco",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 3480.1,
      "Flusso Min": 328.5,
      "Flusso Max": 4453.85,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Nicolosi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.23,
      "Flusso medio": 1046.09,
      "Flusso Min": 878.77,
      "Flusso Max": 1464.58,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Roccalumera",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1169.29,
      "Flusso Min": 1056.12,
      "Flusso Max": 1362.58,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Siculiana",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.52,
      "Flusso medio": 2684.23,
      "Flusso Min": 98.88,
      "Flusso Max": 6346.15,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "6"
    },
    {
      "Identificazione Strada": "Via Villabate",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4876.52,
      "Flusso Min": 3250.5,
      "Flusso Max": 6682.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "6"
    }
  ],
  "7": [
    {
      "Identificazione Strada": "Via Amiterno",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3226.0,
      "Flusso Min": 3069.46,
      "Flusso Max": 3601.62,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Carlo Denina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2093.47,
      "Flusso Min": 1503.92,
      "Flusso Max": 3661.38,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Cesare Baronio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.82,
      "Flusso medio": 3557.25,
      "Flusso Min": 1523.77,
      "Flusso Max": 4980.12,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Gabi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3765.94,
      "Flusso Min": 2546.88,
      "Flusso Max": 5218.96,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Illiria",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 278.48,
      "Flusso Min": 10.96,
      "Flusso Max": 546,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Lemonia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 3557.71,
      "Flusso Min": 171.69,
      "Flusso Max": 6938.77,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Licia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1494.91,
      "Flusso Min": 561.92,
      "Flusso Max": 2008.04,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Matera",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.86,
      "Flusso medio": 3234.13,
      "Flusso Min": 1194.92,
      "Flusso Max": 8031.81,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Via Ponzio Cominio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3323.71,
      "Flusso Min": 891.81,
      "Flusso Max": 9732,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Viale Furio Camillo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4642.97,
      "Flusso Min": 3587.31,
      "Flusso Max": 5028.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Viale Giulio Agricola",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.89,
      "Flusso medio": 2210.01,
      "Flusso Min": 801.12,
      "Flusso Max": 3765.35,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Viale Marco Fulvio Nobiliore",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3328.52,
      "Flusso Min": 195.46,
      "Flusso Max": 11693.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "7"
    },
    {
      "Identificazione Strada": "Viale Metronio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.93,
      "Flusso medio": 1768.25,
      "Flusso Min": 179.54,
      "Flusso Max": 4175.65,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "7"
    }
  ],
  "8": [
    {
      "Identificazione Strada": "Corso Neostiense",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1881.92,
      "Flusso Min": 1881.92,
      "Flusso Max": 1881.92,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Alessandro Severo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.4,
      "Flusso medio": 3604.95,
      "Flusso Min": 307.85,
      "Flusso Max": 11169.69,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Andrea Mantegna",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4838.02,
      "Flusso Min": 3911.88,
      "Flusso Max": 6762.12,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Aristide Leonori",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.6,
      "Flusso medio": 2976.17,
      "Flusso Min": 1680.81,
      "Flusso Max": 3752.08,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via del Porto Fluviale",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1632.94,
      "Flusso Min": 444.23,
      "Flusso Max": 5603.08,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via delle Sette Chiese (Macinghi Strozzi-Ostiense)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.39,
      "Flusso medio": 2050.52,
      "Flusso Min": 233.08,
      "Flusso Max": 7944.58,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Galba",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2564.75,
      "Flusso Min": 1898.42,
      "Flusso Max": 2840.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Giacinto Pullino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4726.14,
      "Flusso Min": 1992.81,
      "Flusso Max": 7723.27,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Giovanni Battista Licata",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.45,
      "Flusso medio": 4439.18,
      "Flusso Min": 2475.12,
      "Flusso Max": 6184.73,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Giovannipoli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.9,
      "Flusso medio": 4083.74,
      "Flusso Min": 3371.88,
      "Flusso Max": 6823.15,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Girolamo Benzoni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.9,
      "Flusso medio": 3688.06,
      "Flusso Min": 1773.46,
      "Flusso Max": 5862.58,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Via Oropa",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 4706.31,
      "Flusso Min": 4706.31,
      "Flusso Max": 4706.31,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Viale di Tor Marancia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4567.53,
      "Flusso Min": 77.08,
      "Flusso Max": 10117.73,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Viale Guglielmo Massaia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.84,
      "Flusso medio": 3431.01,
      "Flusso Min": 1771.5,
      "Flusso Max": 6053.65,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "8"
    },
    {
      "Identificazione Strada": "Ponte dell'Industria",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "8, 11"
    },
    {
      "Identificazione Strada": "Via Ruzzante",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": 8
    }
  ],
  "9": [
    {
      "Identificazione Strada": "Via Bruno Brandellero",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.81,
      "Flusso medio": 4301.54,
      "Flusso Min": 239.42,
      "Flusso Max": 6962.54,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via degli Eroi di Coo",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 916.48,
      "Flusso Min": 211.38,
      "Flusso Max": 1615.5,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via degli Eroi di Trily",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 457.17,
      "Flusso Min": 82.38,
      "Flusso Max": 825.12,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via dei Caduti Civili",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2027.46,
      "Flusso Min": 79.85,
      "Flusso Max": 6419.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via dei Martiri di Marzabotto",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 264.47,
      "Flusso Min": 150.35,
      "Flusso Max": 376.04,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Felice Cascione",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3915.96,
      "Flusso Min": 3358.73,
      "Flusso Max": 11287.73,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Francesco Sapori",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4363.92,
      "Flusso Min": 2623.04,
      "Flusso Max": 9057.81,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Francesco Tumiati",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4948.73,
      "Flusso Min": 3404.77,
      "Flusso Max": 6495.23,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Luigi Chiarini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2663.79,
      "Flusso Min": 1275,
      "Flusso Max": 6403.73,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Marcello Garosi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4832.39,
      "Flusso Min": 3365.08,
      "Flusso Max": 6546.92,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Riccardo Boschiero",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1141.01,
      "Flusso Min": 663.58,
      "Flusso Max": 1645.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Romolo Gigliozzi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.84,
      "Flusso medio": 706.09,
      "Flusso Min": 74.54,
      "Flusso Max": 2572.38,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Vinicio Cortese",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1001.41,
      "Flusso Min": 534.23,
      "Flusso Max": 1500.92,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Via Vitaliano Rotellini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1226.43,
      "Flusso Min": 306.35,
      "Flusso Max": 1879.96,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Viale Beata Vergine del Carmelo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.95,
      "Flusso medio": 4620.94,
      "Flusso Min": 1618.04,
      "Flusso Max": 7697.42,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Viale Cesare Pavese",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4101.61,
      "Flusso Min": 35.88,
      "Flusso Max": 9052.62,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Viale Filippo Tommaso Marinetti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4998.4,
      "Flusso Min": 15.92,
      "Flusso Max": 6653.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Viale Ignazio Silone",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1.0,
      "Flusso medio": 4723.02,
      "Flusso Min": 111.58,
      "Flusso Max": 10324.96,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "9"
    },
    {
      "Identificazione Strada": "Piazzale Ferruccio Parri",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 9
    },
    {
      "Identificazione Strada": "Via Pontina - Laterale",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ; IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": 9
    }
  ],
  "10": [
    {
      "Identificazione Strada": "Corso Duca di Genova",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3043.56,
      "Flusso Min": 1430.77,
      "Flusso Max": 5912.42,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Corso Regina Maria Pia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3610.09,
      "Flusso Min": 2740.96,
      "Flusso Max": 5014.5,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Lungomare Amerigo Vespucci",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1956.63,
      "Flusso Min": 0.12,
      "Flusso Max": 6041.84,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Lungomare Duca degli Abruzzi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 786.61,
      "Flusso Min": 299.65,
      "Flusso Max": 1640.88,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Agostino Chigi",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 4571.65,
      "Flusso Min": 3237.81,
      "Flusso Max": 6032.77,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Albi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.65,
      "Flusso medio": 1004.32,
      "Flusso Min": 0.12,
      "Flusso Max": 2490.12,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Via Alessandro Stradella",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.98,
      "Flusso medio": 1637.87,
      "Flusso Min": 814.73,
      "Flusso Max": 3429.12,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Via Amedeo Bocchi",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.01,
      "Flusso medio": 1773.06,
      "Flusso Min": 240.69,
      "Flusso Max": 3797.54,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Andrea da Garessio (Via dei Romagnoli-Via Lorenzo Nerucci)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 649.75,
      "Flusso Min": 417.69,
      "Flusso Max": 998.77,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Armando Armuzzi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4974.68,
      "Flusso Min": 4258.62,
      "Flusso Max": 5713.5,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Bedonia",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.55,
      "Flusso medio": 1569.14,
      "Flusso Min": 16.27,
      "Flusso Max": 3042,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Carlo Albizzati",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 476.42,
      "Flusso Min": 166.5,
      "Flusso Max": 955.5,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Carlo Avegno",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 458.13,
      "Flusso Min": 311.54,
      "Flusso Max": 809.88,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Carlo Del Greco",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1956.92,
      "Flusso Min": 210.81,
      "Flusso Max": 4437.69,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Corrado Cagli",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.77,
      "Flusso medio": 4378.76,
      "Flusso Min": 35.88,
      "Flusso Max": 7543.04,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Croviana",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 596.62,
      "Flusso Min": 0.23,
      "Flusso Max": 666.58,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Daniele da Samarate",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.82,
      "Flusso medio": 1869.83,
      "Flusso Min": 924.23,
      "Flusso Max": 2983.5,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via dei Monti di San Paolo",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.51,
      "Flusso medio": 1780.76,
      "Flusso Min": 97.38,
      "Flusso Max": 3437.42,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via del Bucintoro",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2494.47,
      "Flusso Min": 2464.96,
      "Flusso Max": 2534.65,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via del Casaletto di Giano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.83,
      "Flusso medio": 628.54,
      "Flusso Min": 245.54,
      "Flusso Max": 1707.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Via del Lido di Castel Porziano",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.97,
      "Flusso medio": 3264.42,
      "Flusso Min": 234.35,
      "Flusso Max": 11547.2,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Via del Rosmarino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.85,
      "Flusso medio": 117.51,
      "Flusso Min": 10.96,
      "Flusso Max": 283.73,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via della Cacciuta",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 351.07,
      "Flusso Min": 172.5,
      "Flusso Max": 702.58,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via della Corazzata",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1582.51,
      "Flusso Min": 1158.69,
      "Flusso Max": 1985.54,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via della Martinica (Ebridi-Idroscalo)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1915.02,
      "Flusso Min": 101.42,
      "Flusso Max": 5669.08,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via delle Azzorre",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.79,
      "Flusso medio": 2977.11,
      "Flusso Min": 26.08,
      "Flusso Max": 6009.92,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via delle Ebridi",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2530.57,
      "Flusso Min": 16.04,
      "Flusso Max": 8012.77,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via delle Fiamme Gialle",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 4577.31,
      "Flusso Min": 2701.15,
      "Flusso Max": 7431.46,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via delle Prore",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1530.43,
      "Flusso Min": 384.69,
      "Flusso Max": 1790.42,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via dell'Idroscalo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.76,
      "Flusso medio": 1572.59,
      "Flusso Min": 234.92,
      "Flusso Max": 2621.77,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Acqua Rossa",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2557.04,
      "Flusso Min": 700.15,
      "Flusso Max": 4837.38,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Dragoncello",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.62,
      "Flusso medio": 792.54,
      "Flusso Min": 48.23,
      "Flusso Max": 1942.27,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Macchia Palocco",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4818.89,
      "Flusso Min": 1662.81,
      "Flusso Max": 9308.08,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Malafede",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.89,
      "Flusso medio": 3982.0,
      "Flusso Min": 553.62,
      "Flusso Max": 22997.54,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Via di Prato Cornelio",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3633.07,
      "Flusso Min": 3066.58,
      "Flusso Max": 4237.27,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Saponara (Acilia-Macchia Saponara)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.98,
      "Flusso medio": 3891.54,
      "Flusso Min": 2412.35,
      "Flusso Max": 7339.73,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via di Saponara (Via del Fosso di Dragoncello -Via Corrado Cagli)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3490.45,
      "Flusso Min": 1882.96,
      "Flusso Max": 7535.65,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Dobbiaco (Via di Castel Porziano-Via Cima Vallona)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1852.13,
      "Flusso Min": 757.5,
      "Flusso Max": 3196.15,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Domenico Baffigo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 453.09,
      "Flusso Min": 40.38,
      "Flusso Max": 1005,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Domenico Morelli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1082.33,
      "Flusso Min": 309.58,
      "Flusso Max": 4025.08,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Domenico Venturini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4124.34,
      "Flusso Min": 1949.42,
      "Flusso Max": 10207.96,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Egidio Garra",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2110.49,
      "Flusso Min": 1591.04,
      "Flusso Max": 2537.54,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Eschilo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.93,
      "Flusso medio": 4378.84,
      "Flusso Min": 439.5,
      "Flusso Max": 7636.96,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Euripide",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.99,
      "Flusso medio": 2207.15,
      "Flusso Min": 24.12,
      "Flusso Max": 3094.15,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Fabiano Landi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4097.31,
      "Flusso Min": 2214.92,
      "Flusso Max": 5744.54,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Fiumalbo",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4675.04,
      "Flusso Min": 311.42,
      "Flusso Max": 5885.88,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Francesco Cilea",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.44,
      "Flusso medio": 4220.14,
      "Flusso Min": 92.77,
      "Flusso Max": 6009,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Giambattista Gelli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2721.14,
      "Flusso Min": 2271.23,
      "Flusso Max": 3322.62,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Giancarlo Passeroni",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.9,
      "Flusso medio": 4022.39,
      "Flusso Min": 1043.65,
      "Flusso Max": 6148.38,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Giovanni Andrea Scartazzini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2568.55,
      "Flusso Min": 2345.88,
      "Flusso Max": 2760.46,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Giuseppe Fagnano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 2744.17,
      "Flusso Min": 1101.35,
      "Flusso Max": 4072.62,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Giuseppe Micali",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1025.3,
      "Flusso Min": 337.04,
      "Flusso Max": 1933.38,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Isole del Capo Verde",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 3985.23,
      "Flusso Min": 482.42,
      "Flusso Max": 7506.81,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Isole Salomone",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.35,
      "Flusso medio": 1224.63,
      "Flusso Min": 433.85,
      "Flusso Max": 2972.88,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Leonardo Mellano",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2962.78,
      "Flusso Min": 1586.54,
      "Flusso Max": 3605.54,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Lorenzo Nerucci",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 80.44,
      "Flusso Min": 17.77,
      "Flusso Max": 137.31,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Maierato",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 665.16,
      "Flusso Min": 373.38,
      "Flusso Max": 1218.81,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Marcello Mastroianni",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.98,
      "Flusso medio": 2156.03,
      "Flusso Min": 69.12,
      "Flusso Max": 4969.27,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Mario Bianco",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3217.7,
      "Flusso Min": 3121.27,
      "Flusso Max": 3664.15,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Melicuccà",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 581.78,
      "Flusso Min": 477.12,
      "Flusso Max": 660.81,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Monsignor Arduino Terzi",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 390.8,
      "Flusso Min": 228.23,
      "Flusso Max": 625.73,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Padre Massaruti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 2527.52,
      "Flusso Min": 27.69,
      "Flusso Max": 4357.62,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Pavullo nel Frignano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 848.93,
      "Flusso Min": 583.96,
      "Flusso Max": 1268.88,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Pietro Romani",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.98,
      "Flusso medio": 2410.73,
      "Flusso Min": 1554.69,
      "Flusso Max": 6937.15,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Reggiolo",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 295.15,
      "Flusso Min": 295.15,
      "Flusso Max": 295.15,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via San Candido",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.49,
      "Flusso medio": 611.48,
      "Flusso Min": 203.08,
      "Flusso Max": 1255.15,
      "Is_TPL": "No",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Torcegno",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1164.56,
      "Flusso Min": 517.62,
      "Flusso Max": 2509.62,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Alessandro Ruspoli",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.99,
      "Flusso medio": 980.86,
      "Flusso Min": 8.88,
      "Flusso Max": 2559.92,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Capitan Casella",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2062.54,
      "Flusso Min": 1822.15,
      "Flusso Max": 2874.35,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Cardinal Ginnasi",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4813.23,
      "Flusso Min": 3479.54,
      "Flusso Max": 6495.12,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Charles Lenormant",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.87,
      "Flusso medio": 2640.19,
      "Flusso Min": 51.81,
      "Flusso Max": 10776.35,
      "Is_TPL": "Sì",
      "Is_GV": "Sì"
    },
    {
      "Identificazione Strada": "Viale del Sommergibile",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 955.04,
      "Flusso Min": 30,
      "Flusso Max": 2379.23,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale della Marina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3748.06,
      "Flusso Min": 3240.39,
      "Flusso Max": 5530.15,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale della Stella Polare",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1396.7,
      "Flusso Min": 855.23,
      "Flusso Max": 3394.96,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale della Vittoria",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.93,
      "Flusso medio": 2330.21,
      "Flusso Min": 249.46,
      "Flusso Max": 4311,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale delle Repubbliche Marinare",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.97,
      "Flusso medio": 1850.11,
      "Flusso Min": 1057.96,
      "Flusso Max": 3267.58,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Desiderato Pietri",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 842.64,
      "Flusso Min": 164.08,
      "Flusso Max": 2455.85,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Enrico Ortolani (Via di Saponara-Viadotto Nuttall)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.98,
      "Flusso medio": 3277.67,
      "Flusso Min": 236.08,
      "Flusso Max": 6242.31,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Paolo Orlando",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3673.23,
      "Flusso Min": 2661.12,
      "Flusso Max": 6354.12,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Vasco de Gama",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 1686.34,
      "Flusso Min": 43.62,
      "Flusso Max": 3649.85,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Vega",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.97,
      "Flusso medio": 1861.73,
      "Flusso Min": 12.69,
      "Flusso Max": 2431.73,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Via Vincenzo Petra",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    },
    {
      "Identificazione Strada": "Viale Alfredo Ottaviani",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "Sì",
      "Is_GV": "No"
    }
  ],
  "11": [
    {
      "Identificazione Strada": "Via Alberto Mancini",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3431.49,
      "Flusso Min": 3337.62,
      "Flusso Max": 3592.5,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via Cristoforo Sabbadino",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3046.97,
      "Flusso Min": 1417.96,
      "Flusso Max": 57832.73,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via dei Grottoni",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3357.09,
      "Flusso Min": 2314.27,
      "Flusso Max": 3837.12,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via del Trullo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 4883.2,
      "Flusso Min": 43.38,
      "Flusso Max": 8155.04,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via di Monte Stallonara",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.37,
      "Flusso medio": 1790.56,
      "Flusso Min": 1021.04,
      "Flusso Max": 4201.62,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "11, 12"
    },
    {
      "Identificazione Strada": "Via Giannetto Valli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1450.32,
      "Flusso Min": 82.04,
      "Flusso Max": 3801.81,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via Piero Colonna",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.97,
      "Flusso medio": 2144.4,
      "Flusso Min": 8.88,
      "Flusso Max": 4323,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Via Senorbi",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 1012.96,
      "Flusso Min": 746.19,
      "Flusso Max": 1396.27,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "11"
    },
    {
      "Identificazione Strada": "Ponte dell'Industria",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "8, 11"
    },
    {
      "Identificazione Strada": "Via di Villa Bonelli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 0,
      "Flusso Min": 0,
      "Flusso Max": 0,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": 11
    }
  ],
  "12": [
    {
      "Identificazione Strada": "Lungotevere Portuense",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.74,
      "Flusso medio": 2746.93,
      "Flusso Min": 89.88,
      "Flusso Max": 9782.54,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "12"
    },
    {
      "Identificazione Strada": "Via della Vignaccia",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.99,
      "Flusso medio": 4076.29,
      "Flusso Min": 2142.69,
      "Flusso Max": 7175.19,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "12"
    },
    {
      "Identificazione Strada": "Via di Monte Stallonara",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.37,
      "Flusso medio": 1790.56,
      "Flusso Min": 1021.04,
      "Flusso Max": 4201.62,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "11, 12"
    },
    {
      "Identificazione Strada": "Via Federico Ozanam",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4573.66,
      "Flusso Min": 3179.93,
      "Flusso Max": 5599.82,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "12"
    },
    {
      "Identificazione Strada": "Via Fonteiana",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.76,
      "Flusso medio": 4723.05,
      "Flusso Min": 184.15,
      "Flusso Max": 8739.46,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "12"
    },
    {
      "Identificazione Strada": "Via Maria Lorenza Longo",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 773.2,
      "Flusso Min": 347.19,
      "Flusso Max": 1051.85,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "12"
    },
    {
      "Identificazione Strada": "Via Nicolò Bettoni",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 2712.06,
      "Flusso Min": 2608.04,
      "Flusso Max": 3024.81,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "12"
    }
  ],
  "13": [
    {
      "Identificazione Strada": "Via Cornelia",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.97,
      "Flusso medio": 3389.14,
      "Flusso Min": 596.54,
      "Flusso Max": 8498.88,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13"
    },
    {
      "Identificazione Strada": "Via di Boccea (Via Villa del Bosco-Via Casalnoceto)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.98,
      "Flusso medio": 2092.52,
      "Flusso Min": 1126.85,
      "Flusso Max": 3348.69,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13, 14"
    },
    {
      "Identificazione Strada": "Via di Casalotti",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3232.25,
      "Flusso Min": 1105.5,
      "Flusso Max": 8468.31,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13"
    },
    {
      "Identificazione Strada": "Via di Pantan Monastero",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.33,
      "Flusso medio": 2326.11,
      "Flusso Min": 1441.5,
      "Flusso Max": 4786.96,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "13"
    },
    {
      "Identificazione Strada": "Via di Selva Candida",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4474.63,
      "Flusso Min": 2130.46,
      "Flusso Max": 6481.04,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13, 14"
    },
    {
      "Identificazione Strada": "Via Federico Patetta",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.77,
      "Flusso medio": 4288.42,
      "Flusso Min": 148.96,
      "Flusso Max": 5998.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "13"
    },
    {
      "Identificazione Strada": "Via Nostra Signora di Lourdes",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0,
      "Flusso medio": 2275.28,
      "Flusso Min": 884.54,
      "Flusso Max": 7168.85,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "13"
    },
    {
      "Identificazione Strada": "Via Umberto Moricca",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 846.38,
      "Flusso Min": 145.27,
      "Flusso Max": 1222.04,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "13"
    }
  ],
  "14": [
    {
      "Identificazione Strada": "Via Braccianese Claudia (Via Cassia-Via Paolo Ferrari)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.81,
      "Flusso medio": 2840.1,
      "Flusso Min": 639,
      "Flusso Max": 7725.35,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "14, 15"
    },
    {
      "Identificazione Strada": "Via della Balduina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.95,
      "Flusso medio": 4890.32,
      "Flusso Min": 768.12,
      "Flusso Max": 9566.08,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "14"
    },
    {
      "Identificazione Strada": "Via di Boccea (Via Villa del Bosco-Via Casalnoceto)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.98,
      "Flusso medio": 2092.52,
      "Flusso Min": 1126.85,
      "Flusso Max": 3348.69,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13, 14"
    },
    {
      "Identificazione Strada": "Via di Selva Candida",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4474.63,
      "Flusso Min": 2130.46,
      "Flusso Max": 6481.04,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "13, 14"
    },
    {
      "Identificazione Strada": "Via Mario Romagnoli",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 4433.13,
      "Flusso Min": 3371.54,
      "Flusso Max": 5494.73,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "14"
    },
    {
      "Identificazione Strada": "Via Trionfale (C.ne Clodia-Evangelisti)",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 4134.26,
      "Flusso Min": 2584.27,
      "Flusso Max": 10907.88,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1, 14"
    }
  ],
  "15": [
    {
      "Identificazione Strada": "Via Bellagio",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.73,
      "Flusso medio": 3956.07,
      "Flusso Min": 475.85,
      "Flusso Max": 6213.23,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Braccianese Claudia (Via Cassia-Via Paolo Ferrari)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.81,
      "Flusso medio": 2840.1,
      "Flusso Min": 639,
      "Flusso Max": 7725.35,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "14, 15"
    },
    {
      "Identificazione Strada": "Via Cesanense (Via della Stazione di Cesano-Via G.Miotto)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 1,
      "Flusso medio": 505.15,
      "Flusso Min": 480.81,
      "Flusso Max": 529.5,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via dei Colli della Farnesina",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.96,
      "Flusso medio": 3589.58,
      "Flusso Min": 555.12,
      "Flusso Max": 11679.03,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via della Giustiniana",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.98,
      "Flusso medio": 3279.33,
      "Flusso Min": 165.92,
      "Flusso Max": 11074.85,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via della Stazione di Cesano (Via G. Patalucci-Via Cesanese)",
      "Is_PGTU": "Sì",
      "Classificazione": "IQ",
      "% PGTU": 0.96,
      "Flusso medio": 3201.26,
      "Flusso Min": 2027.77,
      "Flusso Max": 5910.92,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via della Villa di Livia (Via della Giustiniana-Via P. Davanzo)",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.91,
      "Flusso medio": 2369.36,
      "Flusso Min": 586.04,
      "Flusso Max": 9769.27,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via dell'Isola Farnese",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.88,
      "Flusso medio": 1058.63,
      "Flusso Min": 639.46,
      "Flusso Max": 1454.77,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Edmondo De Amicis",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1.0,
      "Flusso medio": 2265.83,
      "Flusso Min": 1880.08,
      "Flusso Max": 2928.35,
      "Is_TPL": "No",
      "Is_GV": "Sì",
      "Municipio": "1, 15"
    },
    {
      "Identificazione Strada": "Via Francesco Saverio Nitti",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.91,
      "Flusso medio": 3156.35,
      "Flusso Min": 216.58,
      "Flusso Max": 4993.85,
      "Is_TPL": "No",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Frassineto",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.09,
      "Flusso medio": 2721.1,
      "Flusso Min": 10.5,
      "Flusso Max": 8032.04,
      "Is_TPL": "Sì",
      "Is_GV": "Sì",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Ischia di Castro",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 0.75,
      "Flusso medio": 4271.85,
      "Flusso Min": 760.62,
      "Flusso Max": 6987.69,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Oriolo Romano",
      "Is_PGTU": "Sì",
      "Classificazione": "IZ",
      "% PGTU": 1,
      "Flusso medio": 3986.87,
      "Flusso Min": 3815.08,
      "Flusso Max": 4790.65,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Via Osnago",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 1,
      "Flusso medio": 3912.48,
      "Flusso Min": 3142.15,
      "Flusso Max": 4779.58,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Viale Galline Bianche",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.89,
      "Flusso medio": 3121.56,
      "Flusso Min": 85.27,
      "Flusso Max": 6919.5,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    },
    {
      "Identificazione Strada": "Viale Gemona del Friuli",
      "Is_PGTU": "Sì",
      "Classificazione": "Q",
      "% PGTU": 0.87,
      "Flusso medio": 2358.7,
      "Flusso Min": 6.58,
      "Flusso Max": 3990.35,
      "Is_TPL": "Sì",
      "Is_GV": "No",
      "Municipio": "15"
    }
  ]
};
